language: php

sudo: required

services:
- docker

php:
  - 7.1
  - 7.2

before_install:
  - cd tests
  - docker-compose up -d
  - cd ..
# - bash ./tests/install-sqlsrv.sh

install:
  - composer install --no-interaction --prefer-source

script:
  - vendor/bin/phpunit --coverage-clover=coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash) -f coverage.xml

jobs:
  include:
  # PHP Nightly builds does not support SQLServer yet
  - stage: Test
    php: nightly
    before_install:
    - cd tests
    - docker-compose up -d
    - cd ..
    script:
    - vendor/bin/phpunit tests/ORM/Driver/SQLite
    - vendor/bin/phpunit tests/ORM/Driver/Postgres